[package]
name = "swaygrouptool"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.21", features = ["derive"] }
serde = "1.0.186"
serde_json = "1.0.105"
swayipc = "3.0.1"

[dev-dependencies]
serial_test = "2.0.0"
